[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
monitor_port = /dev/cu.usbmodem1101
upload_port = COM5
upload_protocol = esptool
build_unflags = 
    -std=gnu++11
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -std=gnu++17
    -Wall
board_build.partitions = huge_app.csv
lib_deps =
    lovyan03/LovyanGFX
    tzapu/WiFiManager
    mathieucarbou/ESP Async WebServer
    mathieucarbou/AsyncTCP
    bblanchon/ArduinoJson